det_thresh:
  type: uniform
  default: 0.30
  range: [0.1, 0.6]

max_age:
  type: randint
  default: 30
  range: [10, 61, 10]

min_hits:
  type: randint
  default: 1
  range: [1, 6]

iou_threshold:
  type: uniform
  default: 0.30
  range: [0.1, 0.4]

delta_t:
  type: randint
  default: 3
  range: [1, 6]

asso_func:
  type: choice
  default: iou
  options: ['iou', 'giou', 'diou', 'ciou', 'hmiou']

inertia:
  type: uniform
  default: 0.20
  range: [0.1, 0.4]

w_association_emb:
  type: uniform
  default: 0.50
  range: [0.5, 0.9]

alpha_fixed_emb:
  type: uniform
  default: 0.95
  range: [0.9, 0.999]

aw_param:
  type: uniform
  default: 0.50
  range: [0.3, 0.7]

embedding_off:
  type: choice
  default: True
  options: [True, False]

cmc_off:
  type: choice
  default: True
  options: [True, False]

aw_off:
  type: choice
  default: True
  options: [True, False]

Q_xy_scaling:
  type: uniform
  default: 0.01
  range: [0.01, 1]

Q_s_scaling:
  type: uniform
  default: 0.0001
  range: [0.0001, 1]
